name: Build Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 5.7.0
      uses: actions/setup-node@v2
      with:
        node-version: '5.7.0'

    - name: Install dependencies
      run: |
        npm install -g pxt
        pxt target microbit
        pxt install

    - name: Build
      run: pxt build
